### ISSUE TITLE
Pipeline issue - hm_rasterscan

### ISSUE THREAD

**Issue by keflavich** [ACES-CMZ/reduction_ACES#277]
I'm not clear what this error is.   I've never seen it before.  Based on the name, I suspect it might be from the TP pipeline?

```
CASA 6.4.3.2 -- Common Astronomy Software Applications [6.4.3.2]
*** ALMA scriptForPI ***
Found pipeline manifest(s):
['member.uid___A001_X15a0_Xaa.hsd_calimage.pipeline_manifest.xml']
Unpacking member.uid___A001_X15a0_Xaa.auxproducts.tgz ...
Found  9867699202  MB of available free disk space.
Expect to need up to  278553.0  MB of free disk space.
Found the following ASDMs: ['uid___A002_Xfe62c1_X9637.asdm.sdm', 'uid___A002_Xfe62c1_X1eb2.asdm.sdm', 'uid___A002_Xfe62c1_X8dda.asdm.sdm', 'uid___A002_Xfe62c1_Xa26.asdm.sdm', 'uid___A002_Xfe62c1_X1338.asdm.sdm', 'uid___A002_Xfe62c1_X2dbc.asdm.sdm']
Creating destination directory for calibrated data.
Processing the ASDMs  ['uid___A002_Xfe62c1_Xa26', 'uid___A002_Xfe62c1_X1338', 'uid___A002_Xfe62c1_X1eb2', 'uid___A002_Xfe62c1_X2dbc', 'uid___A002_Xfe62c1_X8dda', 'uid___A002_Xfe62c1_X9637']  using pipeline restore.
now running  member.uid___A001_X15a0_Xaa.hsd_calimage.casa_piperestorescript.py
2022-10-05 04:03:07 INFO: Tracking execution duration for context: pipeline-20221005T040307
ESC[31m2022-10-05 04:03:07 ERROR: Error creating hard link to CASA logESC[0m
ESC[33m2022-10-05 04:03:07 WARNING: Reverting to symbolic link to CASA log. This is unsupported!ESC[0m
2022-10-05 04:03:08     SEVERE  h_init::pipeline.infrastructure.launcher::casa  Error creating hard link to CASA log
2022-10-05 04:03:08     WARN    h_init::pipeline.infrastructure.launcher::casa  Reverting to symbolic link to CASA log. This is unsupported!
2022-10-05 04:03:07 INFO: Setting plot level to 'default'
2022-10-05 04:03:07 INFO: Saving context: pipeline-20221005T040307.context
Traceback (most recent call last):
  File "/blue/adamginsburg/adamginsburg/casa/casa-6.4.3-2-pipeline-2021.3.0.17/lib/py/lib/python3.6/site-packages/casashell/private/init_system.py", line 238, in __evprop__
    exec(stmt)
  File "<string>", line 1, in <module>
  File "/blue/adamginsburg/adamginsburg/casa/casa-6.4.3-2-pipeline-2021.3.0.17/lib/py/lib/python3.6/site-packages/casashell/private/init_system.py", line 175, in execfile
    newglob = run_path( filename, init_globals=globals )
  File "/blue/adamginsburg/adamginsburg/casa/casa-6.4.3-2-pipeline-2021.3.0.17/lib/py/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/blue/adamginsburg/adamginsburg/casa/casa-6.4.3-2-pipeline-2021.3.0.17/lib/py/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/blue/adamginsburg/adamginsburg/casa/casa-6.4.3-2-pipeline-2021.3.0.17/lib/py/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "member.uid___A001_X15a0_Xaa.scriptForPI.py", line 555, in <module>
  File "/blue/adamginsburg/adamginsburg/casa/casa-6.4.3-2-pipeline-2021.3.0.17/lib/py/lib/python3.6/site-packages/casashell/private/init_system.py", line 175, in execfile
    newglob = run_path( filename, init_globals=globals )
  File "/blue/adamginsburg/adamginsburg/casa/casa-6.4.3-2-pipeline-2021.3.0.17/lib/py/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/blue/adamginsburg/adamginsburg/casa/casa-6.4.3-2-pipeline-2021.3.0.17/lib/py/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/blue/adamginsburg/adamginsburg/casa/casa-6.4.3-2-pipeline-2021.3.0.17/lib/py/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "../../script/member.uid___A001_X15a0_Xaa.hsd_calimage.casa_piperestorescript.py", line 13, in <module>
    hsd_restoredata(vis=['uid___A002_Xfe62c1_Xa26', 'uid___A002_Xfe62c1_X1338', 'uid___A002_Xfe62c1_X1eb2', 'uid___A002_Xfe62c1_X2dbc', 'uid___A002_Xfe62c1_X8dda', 'uid___A002_Xfe62c1_X9637'], session=['session_1', 'session_2', 'session_2', 'session_3', 'session_4', 'session_4'], ocorr_mode='ao', hm_rasterscan='time')
TypeError: __call__() got an unexpected keyword argument 'hm_rasterscan'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[55989,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by keflavich** [comment]
(but we're not supposed to be running the TP pipeline...)
